accepted = [
    "GPL-3.0",                        # Ol' reliable
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",                            # AKA Expat license
    "Unicode-3.0",
    "MPL-2.0",                        # Mozilla Public License
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "ISC",
    "NCSA",
    "BSL-1.0",                        # Boost Public License
]

# Scan only what tRust is using. Downstream dependencies complying with their
# licenses should be their responsonilty.
ignore-transitive-dependencies = true

# Build dependencies are not shipped as part of the actual software binary. As
# such, they don't need to be attributed since we're not distributing any
# modified versions of these crates (even linking). This is only really to slim
# down the NOTICES file. In the astronomically rare case where people want this
# on, I will happily do so.
ignore-build-dependencies = true
