import { Button, StandardButton } from "std-widgets.slint";

export component TodoPopup inherits Window {
    height: 150px;
    in-out property <bool> popup_visible;
    callback hide_todo_popup();

    GridLayout {
        spacing: 15px;
        padding: 50px;

        Text {
            text: "Unimplemented Feature";
            color: black;
            row: 0;
            rowspan: 3;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        StandardButton {
            kind: ok;
            row: 3;
            rowspan: 1;
            clicked => {
                hide_todo_popup();
            }
        }
    }
}

export component MainWindow inherits Window {
    min-height: 250px;
    min-width: 800px;
    title: "tRust";

    in property <string> balance;

    callback show_todo_popup();

    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "Open Existing Ledger";
                activated => {
                    show_todo_popup();
                }
            }
        }

        Menu {
            title: "View";
            MenuItem {
                title: "Category Breakdown";
                activated => {
                    show_todo_popup();
                }
            }
        }
    }

    GridLayout {
        padding: 10px;
        spacing: 10px;
        Button {
            text: "Button 1";
            col: 0;
            row: 0;
        }

        Button {
            text: "Button 1";
            col: 0;
            row: 1;
        }

        Button {
            text: "Button 1";
            col: 0;
            row: 2;
        }

        Text {
            min-width: 16px;
            min-height: 16px;
            horizontal-alignment: center;
            text: "Total Cash Balance";
            font-weight: 1000;
            row: 0;
            col: 1;
            colspan: 3;
        }

        Text {
            min-width: 16px;
            min-height: 16px;
            horizontal-alignment: center;
            text: balance;
            row: 1;
            col: 1;
            colspan: 3;
        }

        Rectangle {
            background: gray;
            row: 3;
            col: 0;
            colspan: 4;
        }
    }
}
