//  Copyright (C) 2024  Sebastian Pineda (spineda.wpi.alum@gmail.com)
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program. If not, see <https://www.gnu.org/licenses/>
//
//  main_window.slint - design of main window and friends

import { Button, StandardButton } from "std-widgets.slint";

export component MissingConfigPopup inherits Window {
    height: 150px;
    in-out property <bool> popup_visible;
    callback hide_todo_popup();
    title: "Could not find trust.ledger";

    GridLayout {
        spacing: 15px;
        padding: 50px;

        Text {
            text: "Could not find a valid trust.ledger (or other) file.";
            color: black;
            row: 0;
            rowspan: 2;
            colspan: 2;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
        Text {
            text: "How would you like to proceed?";
            color: black;
            row: 1;
            rowspan: 2;
            colspan: 2;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Button {
            text: "Open Existing...";
            row: 3;
            col: 0;
            clicked => {
                hide_todo_popup();
            }
        }
        Button {
            text: "New Ledger...";
            row: 3;
            col: 1;
            clicked => {
                hide_todo_popup();
            }
        }
    }
}

export component TodoPopup inherits Window {
    height: 150px;
    in-out property <bool> popup_visible;
    callback hide_todo_popup();

    GridLayout {
        spacing: 15px;
        padding: 50px;

        Text {
            text: "Unimplemented Feature";
            color: black;
            row: 0;
            rowspan: 3;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        StandardButton {
            kind: ok;
            row: 3;
            rowspan: 1;
            clicked => {
                hide_todo_popup();
            }
        }
    }
}

export component MainWindow inherits Window {
    min-height: 250px;
    min-width: 800px;
    title: "tRust";

    in property <string> balance;

    callback show_todo_popup();

    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "Open Existing Ledger";
                activated => {
                    show_todo_popup();
                }
            }
        }

        Menu {
            title: "View";
            MenuItem {
                title: "Category Breakdown";
                activated => {
                    show_todo_popup();
                }
            }
        }
    }

    GridLayout {
        padding: 10px;
        spacing: 10px;
        Button {
            text: "Button 1";
            col: 0;
            row: 0;
        }

        Button {
            text: "Button 1";
            col: 0;
            row: 1;
        }

        Button {
            text: "Button 1";
            col: 0;
            row: 2;
        }

        Text {
            min-width: 16px;
            min-height: 16px;
            horizontal-alignment: center;
            text: "Total Cash Balance";
            font-weight: 1000;
            row: 0;
            col: 1;
            colspan: 3;
        }

        Text {
            min-width: 16px;
            min-height: 16px;
            horizontal-alignment: center;
            text: balance;
            row: 1;
            col: 1;
            colspan: 3;
        }

        Rectangle {
            background: gray;
            row: 3;
            col: 0;
            colspan: 4;
        }
    }
}
